# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'robottelemetry.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1024, 720)
        Dialog.setMinimumSize(QtCore.QSize(1024, 720))
        Dialog.setMaximumSize(QtCore.QSize(1024, 720))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../img/LSTME logo RGB.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 1001, 701))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2.setMinimumSize(QtCore.QSize(70, 70))
        self.label_2.setMaximumSize(QtCore.QSize(180, 180))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../img/gyro.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.gridLayoutWidget_2)
        self.textBrowser.setMinimumSize(QtCore.QSize(120, 0))
        self.textBrowser.setMaximumSize(QtCore.QSize(120, 90))
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_3.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.gridLayoutWidget_2)
        self.textBrowser_2.setMinimumSize(QtCore.QSize(120, 90))
        self.textBrowser_2.setMaximumSize(QtCore.QSize(120, 90))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayout_3.addWidget(self.textBrowser_2, 1, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.GyroX = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.GyroX.setMaximumSize(QtCore.QSize(50, 30))
        self.GyroX.setObjectName("GyroX")
        self.gridLayout_4.addWidget(self.GyroX, 0, 1, 1, 1)
        self.GyroZ = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.GyroZ.setMaximumSize(QtCore.QSize(50, 30))
        self.GyroZ.setObjectName("GyroZ")
        self.gridLayout_4.addWidget(self.GyroZ, 3, 1, 1, 1)
        self.GyroY = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.GyroY.setMaximumSize(QtCore.QSize(50, 30))
        self.GyroY.setObjectName("GyroY")
        self.gridLayout_4.addWidget(self.GyroY, 2, 1, 1, 1)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.gridLayoutWidget_2)
        self.textBrowser_3.setMaximumSize(QtCore.QSize(100, 30))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.gridLayout_4.addWidget(self.textBrowser_3, 0, 0, 1, 1)
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.gridLayoutWidget_2)
        self.textBrowser_4.setMaximumSize(QtCore.QSize(100, 30))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.gridLayout_4.addWidget(self.textBrowser_4, 2, 0, 1, 1)
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.gridLayoutWidget_2)
        self.textBrowser_5.setMaximumSize(QtCore.QSize(100, 30))
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.gridLayout_4.addWidget(self.textBrowser_5, 3, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 0, 1, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.AccelerometerY = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.AccelerometerY.setMaximumSize(QtCore.QSize(50, 30))
        self.AccelerometerY.setObjectName("AccelerometerY")
        self.gridLayout_5.addWidget(self.AccelerometerY, 2, 1, 1, 1)
        self.textBrowser_8 = QtWidgets.QTextBrowser(self.gridLayoutWidget_2)
        self.textBrowser_8.setMaximumSize(QtCore.QSize(100, 30))
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.gridLayout_5.addWidget(self.textBrowser_8, 3, 0, 1, 1)
        self.AccelerometerX = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.AccelerometerX.setMaximumSize(QtCore.QSize(50, 30))
        self.AccelerometerX.setObjectName("AccelerometerX")
        self.gridLayout_5.addWidget(self.AccelerometerX, 0, 1, 1, 1)
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.gridLayoutWidget_2)
        self.textBrowser_6.setMaximumSize(QtCore.QSize(100, 30))
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.gridLayout_5.addWidget(self.textBrowser_6, 0, 0, 1, 1)
        self.AccelerometerZ = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.AccelerometerZ.setMaximumSize(QtCore.QSize(50, 50))
        self.AccelerometerZ.setObjectName("AccelerometerZ")
        self.gridLayout_5.addWidget(self.AccelerometerZ, 3, 1, 1, 1)
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.gridLayoutWidget_2)
        self.textBrowser_7.setMaximumSize(QtCore.QSize(100, 30))
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.gridLayout_5.addWidget(self.textBrowser_7, 2, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_5, 1, 1, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_3)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 2, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser_9 = QtWidgets.QTextBrowser(self.gridLayoutWidget_2)
        self.textBrowser_9.setMinimumSize(QtCore.QSize(130, 30))
        self.textBrowser_9.setMaximumSize(QtCore.QSize(130, 30))
        self.textBrowser_9.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.textBrowser_9.setObjectName("textBrowser_9")
        self.verticalLayout.addWidget(self.textBrowser_9)
        self.MotorL = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.MotorL.setMaximumSize(QtCore.QSize(50, 30))
        self.MotorL.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.MotorL.setObjectName("MotorL")
        self.verticalLayout.addWidget(self.MotorL)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label.setMaximumSize(QtCore.QSize(300, 300))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../img/robot.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textBrowser_10 = QtWidgets.QTextBrowser(self.gridLayoutWidget_2)
        self.textBrowser_10.setMinimumSize(QtCore.QSize(130, 30))
        self.textBrowser_10.setMaximumSize(QtCore.QSize(130, 30))
        self.textBrowser_10.setObjectName("textBrowser_10")
        self.verticalLayout_2.addWidget(self.textBrowser_10)
        self.MotorR = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.MotorR.setMaximumSize(QtCore.QSize(50, 30))
        self.MotorR.setObjectName("MotorR")
        self.verticalLayout_2.addWidget(self.MotorR)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.LightSensor2 = QtWidgets.QProgressBar(self.gridLayoutWidget_2)
        self.LightSensor2.setMaximumSize(QtCore.QSize(60, 120))
        self.LightSensor2.setProperty("value", 24)
        self.LightSensor2.setAlignment(QtCore.Qt.AlignCenter)
        self.LightSensor2.setOrientation(QtCore.Qt.Vertical)
        self.LightSensor2.setObjectName("LightSensor2")
        self.gridLayout.addWidget(self.LightSensor2, 2, 2, 1, 1)
        self.Ultrasonic2 = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.Ultrasonic2.setMaximumSize(QtCore.QSize(60, 30))
        self.Ultrasonic2.setObjectName("Ultrasonic2")
        self.gridLayout.addWidget(self.Ultrasonic2, 1, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(200, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 0, 1, 1)
        self.LightSensor5 = QtWidgets.QProgressBar(self.gridLayoutWidget_2)
        self.LightSensor5.setMaximumSize(QtCore.QSize(60, 120))
        self.LightSensor5.setProperty("value", 24)
        self.LightSensor5.setAlignment(QtCore.Qt.AlignCenter)
        self.LightSensor5.setOrientation(QtCore.Qt.Vertical)
        self.LightSensor5.setObjectName("LightSensor5")
        self.gridLayout.addWidget(self.LightSensor5, 2, 5, 1, 1)
        self.LightSensor4 = QtWidgets.QProgressBar(self.gridLayoutWidget_2)
        self.LightSensor4.setMaximumSize(QtCore.QSize(60, 120))
        self.LightSensor4.setProperty("value", 24)
        self.LightSensor4.setAlignment(QtCore.Qt.AlignCenter)
        self.LightSensor4.setOrientation(QtCore.Qt.Vertical)
        self.LightSensor4.setObjectName("LightSensor4")
        self.gridLayout.addWidget(self.LightSensor4, 2, 4, 1, 1)
        self.LightSensor3 = QtWidgets.QProgressBar(self.gridLayoutWidget_2)
        self.LightSensor3.setMaximumSize(QtCore.QSize(60, 120))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.LightSensor3.setFont(font)
        self.LightSensor3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LightSensor3.setProperty("value", 24)
        self.LightSensor3.setAlignment(QtCore.Qt.AlignCenter)
        self.LightSensor3.setOrientation(QtCore.Qt.Vertical)
        self.LightSensor3.setObjectName("LightSensor3")
        self.gridLayout.addWidget(self.LightSensor3, 2, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(200, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 6, 1, 1)
        self.Ultrasonic1 = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.Ultrasonic1.setMaximumSize(QtCore.QSize(60, 30))
        self.Ultrasonic1.setObjectName("Ultrasonic1")
        self.gridLayout.addWidget(self.Ultrasonic1, 1, 2, 1, 1)
        self.Ultrasonic3 = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.Ultrasonic3.setMaximumSize(QtCore.QSize(60, 30))
        self.Ultrasonic3.setObjectName("Ultrasonic3")
        self.gridLayout.addWidget(self.Ultrasonic3, 1, 4, 1, 1)
        self.LightSensor1 = QtWidgets.QProgressBar(self.gridLayoutWidget_2)
        self.LightSensor1.setMaximumSize(QtCore.QSize(60, 120))
        self.LightSensor1.setProperty("value", 24)
        self.LightSensor1.setAlignment(QtCore.Qt.AlignCenter)
        self.LightSensor1.setOrientation(QtCore.Qt.Vertical)
        self.LightSensor1.setObjectName("LightSensor1")
        self.gridLayout.addWidget(self.LightSensor1, 2, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ComPort = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.ComPort.setMaximumSize(QtCore.QSize(100, 50))
        self.ComPort.setMaxLength(100)
        self.ComPort.setObjectName("ComPort")
        self.horizontalLayout_3.addWidget(self.ComPort)
        self.ConnectButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ConnectButton.setMaximumSize(QtCore.QSize(100, 50))
        self.ConnectButton.setObjectName("ConnectButton")
        self.horizontalLayout_3.addWidget(self.ConnectButton)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Gyro</p></body></html>"))
        self.textBrowser_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Akcelerometer</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">X:</p></body></html>"))
        self.textBrowser_4.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Y:</p></body></html>"))
        self.textBrowser_5.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Z:</p></body></html>"))
        self.textBrowser_8.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Z:</p></body></html>"))
        self.textBrowser_6.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">X:</p></body></html>"))
        self.textBrowser_7.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Y:</p></body></html>"))
        self.textBrowser_9.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Left Motor Speed</p></body></html>"))
        self.textBrowser_10.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Right Motor Speed</p></body></html>"))
        self.ConnectButton.setText(_translate("Dialog", "Connect"))
